// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// The rest of the app keeps secrets in .env.local (Next.js's own convention,
// loaded automatically by `next dev`/`next build`) rather than a separate
// .env — load the same file here so the Prisma CLI sees DATABASE_URL too.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations need a direct (non-pooled) connection — Supabase's pgbouncer
  // connection (DATABASE_URL, used at app runtime in src/lib/db.ts) runs in
  // transaction-pooling mode, which doesn't support the prepared statements
  // and advisory locks `prisma migrate` relies on.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
